version: 1

# 定义MCP功能模块
modules:
  - name: 'actions'
    enabled: true
    description: '允许AI访问和修复GitHub Actions工作流'

  - name: 'code-suggestions'
    enabled: true
    description: '提供代码建议和自动修复'

  - name: 'issue-triage'
    enabled: true
    description: '帮助分类和处理issues'

# GitHub Copilot设置
copilot:
  enabled: true
  sensitivity: 'medium' # 可选: low, medium, high

# 项目上下文设置
context:
  description: '一个使用Next.js和Express的购物系统项目'
  keywords:
    - 'shopping-system'
    - 'next.js'
    - 'express'
    - 'mongodb'
    - 'pnpm'

  # 重要文件和目录
  important_files:
    - 'apps/api/src/index.ts'
    - 'apps/web/src/pages/index.tsx'
    - '.github/workflows/deploy.yml'

  # 上下文提示
  hints:
    - '项目使用pnpm workspace管理前后端包'
    - '后端API使用Express和MongoDB'
    - '前端使用Next.js框架'
    - '使用GitHub Actions进行CI/CD'

# AI权限设置
permissions:
  workflow: 'write' # 允许AI修改工作流
  issues: 'write' # 允许AI处理issues
  pull_requests: 'write' # 允许AI处理PRs

# 自定义触发器
triggers:
  workflow_failure:
    actions:
      - 'suggest_fix'
      - 'create_issue'
  issue_created:
    actions:
      - 'auto_label'
      - 'suggest_assignee'
