branch-defaults:
  main:
    environment: shopping-api-prod
    group_suffix: null

global:
  application_name: shopping-system-api
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: ap-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
