import type { Product } from "./types"

export const featuredProducts: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    price: 79.99,
    originalPrice: 99.99,
    category: "Electronics",
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Headphones",
  },
  {
    id: "2",
    name: "Smart Watch with Heart Rate Monitor",
    price: 129.99,
    category: "Electronics",
    rating: 4.2,
    reviewCount: 95,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Smart+Watch",
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    price: 24.99,
    originalPrice: 29.99,
    category: "Clothing",
    rating: 4.0,
    reviewCount: 87,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=T-Shirt",
  },
  {
    id: "4",
    name: "Non-Stick Cooking Set",
    price: 89.99,
    originalPrice: 119.99,
    category: "Home & Kitchen",
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Cooking+Set",
  },
]

export const allProducts: Product[] = [
  ...featuredProducts,
  {
    id: "5",
    name: "Wireless Charging Pad",
    price: 29.99,
    category: "Electronics",
    rating: 4.1,
    reviewCount: 76,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Charging+Pad",
  },
  {
    id: "6",
    name: "Portable Bluetooth Speaker",
    price: 49.99,
    originalPrice: 69.99,
    category: "Electronics",
    rating: 4.3,
    reviewCount: 112,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Speaker",
  },
  {
    id: "7",
    name: "Slim Fit Jeans",
    price: 39.99,
    category: "Clothing",
    rating: 3.9,
    reviewCount: 64,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Jeans",
  },
  {
    id: "8",
    name: "Winter Jacket",
    price: 89.99,
    originalPrice: 119.99,
    category: "Clothing",
    rating: 4.4,
    reviewCount: 92,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Jacket",
  },
  {
    id: "9",
    name: "Stainless Steel Water Bottle",
    price: 19.99,
    category: "Home & Kitchen",
    rating: 4.6,
    reviewCount: 143,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Water+Bottle",
  },
  {
    id: "10",
    name: "Coffee Maker",
    price: 79.99,
    originalPrice: 99.99,
    category: "Home & Kitchen",
    rating: 4.2,
    reviewCount: 87,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Coffee+Maker",
  },
  {
    id: "11",
    name: "Bestselling Novel",
    price: 14.99,
    category: "Books",
    rating: 4.8,
    reviewCount: 215,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Novel",
  },
  {
    id: "12",
    name: "Cookbook Collection",
    price: 34.99,
    originalPrice: 44.99,
    category: "Books",
    rating: 4.5,
    reviewCount: 78,
    inStock: true,
    image: "/placeholder.svg?height=300&width=300&text=Cookbook",
  },
]
