name: 部署到AWS Lambda

on:
  push:
    branches: [main]
    paths:
      - 'apps/api/**'
      - 'packages/shared/**'
      - '.github/workflows/deploy-lambda-new.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install

      - name: 构建shared包
        run: cd packages/shared && pnpm build

      - name: 构建API包
        run: cd apps/api && pnpm build

      - name: 部署到AWS Lambda
        run: |
          STAGE="${{ github.event.inputs.environment || 'production' }}"
          cd apps/api && pnpm dlx serverless@3 deploy --stage $STAGE
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: 通知部署状态
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Lambda函数部署成功"
          else
            echo "Lambda函数部署失败"
          fi
