name: MCP自动化

on:
  workflow_run:
    workflows: ['*']
    types:
      - completed
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  mcp-process:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure' || github.event_name == 'issues' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置MCP上下文
        id: mcp-context
        uses: github/mcp-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 处理工作流失败
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "工作流失败: ${{ github.event.workflow_run.name }}"
          echo "正在处理MCP上下文..."
          echo "上下文ID: ${{ steps.mcp-context.outputs.context-id }}"

      - name: 处理Issue
        if: ${{ github.event_name == 'issues' }}
        run: |
          echo "处理新Issue: #${{ github.event.issue.number }}"
          echo "正在应用MCP分类..."

      - name: 处理Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "处理Pull Request: #${{ github.event.pull_request.number }}"
          echo "正在应用MCP代码审查..."
